# Generated by Django 4.1.7 on 2023-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorchange',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
